version: '3'

volumes:
  standalone_volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind

services:
  # Dependencies
  web:
    build: .
    image: quo/quo-core:1.0.0
    working_dir: /quo-core
    command: npm run serve
    volumes:
      - standalone_volume:/quo-core
    ports:
      - "3000:3000"
